# Teoría de la Información y la Codificación
## Tarea: Códigos lineales


# Autor: 

Rellene la siguiente información:

 - Estudiante (nombre y apellidos): Cristina Sánchez Justicia 
 - DNI/NIE/Pasaporte: 77689772G
 - Grupo: 4º CSI 
 - Curso académico: 4º  



__Yo, como estudiante de la asignatura, aseguro que la elaboración de estos ejercicios ha sido realizada de forma individual, sin incurrir en copias parciales o totales de código fuente o documentación, y acepto las repercusiones que conllevaría si esto no fuese así.__


# Respuestas a las cuestiones teóricas:
__Definición de códigos lineales__ <br>
<br>
Un código lineal es in subespacio vectorial sobre un cuerpo GF(q) (para nosotros q es 2 ya que está en binario). <br>
<br>
Un cuerpo GF(q) es un concepto matemático donde tenemos definidas las operaciones + y * con sus respectivas propiedades, de forma que el resultado de aplicar las operaciones pertenece al subespacio vectorial de nuestro código. El código es modular GF(q) = {0, 1, 2, ..., q-1} <br>
<br>
En específico, estudiamos campos de Galois, que son códigos de longitud fija n. <br>
<br>
Juntando todas las palabras del código podemos obtener una matriz que es la base del espacio vectorial. Si eliminamos las filas que son linealmente dependientes, obetenemos la matriz generadora del código. <br>
<br>
La matriz generadora se obtiene concatenando la matriz de paridad con la matriz de identidad M(C) = [P I]. <br>
<br>
__Codificación y decodificación de códigos lineales__ <br>
<br>
Las palabras a codificar tienen longitud k y las palabras codificadas tienen longitud n. 
Para codificarlas, multiplicamos la palabra de longitud n por la matriz de codificación. Para decodificarlas, solo tenemos que mirar los últimos k bits de la palabra. Aunque antes de decodificar debemos asegurarnos de que no hay errores en la palabra. <br>
<br>
__Corrección de errores en códigos lineales. Relación con la distancia del código__ <br>
<br>
Para la comprobación de errores se usa la Matriz de Comprobación de Paridad H(C) = [I T] donde T es la transpuesta de P. <br>
<br>
Cuando multiplicamos la palabra enviada por H(C) obtenemos el síndrome del código, que es un vector que indica donde hay errores. Si todos sus elementos son 0, no hay errores y se puede descodificar. Si el síndrome tiene algún valor no nulo, en el caso de los codigos en GF(2) solo tenemos que cambiar ese bit para obtener la respuesta correcta. <br> 
<br>
La distancia de un código lineal es el mínimo número de diferencias que hay entre todas las palabras. 
<br>
Cuando la distancia del código es d, podemos corregir hasta (d-1)/2 errores. En nuestro caso como la distancia del código es 5, podemos corregir hasta (5-1)/2 = 2 errores. 

In [2]:

#imports
import numpy as np

In [3]:

# Declaración de constantes a usar ( en caso de ser necesario )
FicheroMatrizCodificacion= '47_36_5.txt'
n= 47 # Longitud del código de bloque
k= 36 # 2^k mensajes posibles por la fuente
d= 5 # Distancia del código




In [4]:

# Función que tiene como entrada:
#  - filename: una ruta a fichero con la matriz generadora de un código lineal
#  - k: la dimensión del código (2^k mensajes posibles a codificar)
#  - n: la longitud del código de bloque
# Da como salida un array 2D con la matriz leída en formato [P I], para codificar con un código lineal
# sobre GF(2) mensajes de longitud k en un código de bloque de dimensión n
def LeerMatrizCodificacion(filename, k, n):
    M= np.loadtxt(filename, dtype=np.uint8)
    return M

M= LeerMatrizCodificacion(FicheroMatrizCodificacion, k, n)

In [5]:

# Generación aleatoria de una palabra de k bits
# Función que tiene como entrada k, la longitud de un código, y genera
# una palabra de un código de longitud k sobre GF(2)
def GenerarPalabraAleatoria(k):
    palabra= np.random.randint(0, 2, k)
    return palabra


# Función que tiene como entrada una palabra de un código sobre GF(2) y genera un error de 1 bit en dicha palabra
def InsertarError1bit(palabra):
    pos= np.random.randint(0, len(palabra))
    palabra[pos]= 1-palabra[pos]

    
# Función que tiene como entrada una palabra de un código sobre GF(2) y genera un error de 2 bits en dicha palabra
def InsertarError2bits(palabra):
    pos1= np.random.randint(0, len(palabra))
    palabra[pos1]= 1-palabra[pos1]
    pos2= np.random.randint(0, len(palabra))
    while (pos1 == pos2):
        pos2= np.random.randint(0, len(palabra))
    palabra[pos2]= 1-palabra[pos2]

    
# Función que tiene como entrada una palabra de un código sobre GF(2) y genera un error de 3 bits en dicha palabra
def InsertarError3bits(palabra):
    pos1= np.random.randint(0, len(palabra))
    palabra[pos1]= 1-palabra[pos1]
    pos2= np.random.randint(0, len(palabra))
    while (pos1 == pos2):
        pos2= np.random.randint(0, len(palabra))
    palabra[pos2]= 1-palabra[pos2]
    pos3= np.random.randint(0, len(palabra))
    while (pos3 == pos2 or pos3 == pos1):
        pos3= np.random.randint(0, len(palabra))
    palabra[pos3]= 1-palabra[pos3]
    



In [18]:
# Función Codificar
# entradas: 
#          - palabra de un código uniforme de longitud k sobre GF(2) 
#          - matriz de codificación desde la palabra del código dado a un código de bloque de 
#            longitud n.
# Devuelve: 
#          - palabra del código de bloque que codifica a la palabra de entrada

def Codificar(palabra, matrizCodificacion):
    return np.matmul(palabra,matrizCodificacion.T) 


# Entrada: 
#         - palabra de un código de bloque de n bits  
#         - la matriz de codificación, sobre GF(2),
# Salida: 
#         - código uniforme de longitud k que decodifica a la palabra del código de bloque

def Decodificar(palabra, M): 
    return palabra[n-k:]



In [7]:

# Efecto: 
#        - realiza el cálculo de la matriz de control de paridad del código, H(C), y la devuelve 
#          como salida.
# Entrada: 
#        - matriz de codificación M(C) en formato M= [P I]
# Salida: 
#        - matriz de control de paridad del código
def paridad(M): 
    return M



# Entrada:
#         - Matriz de codificación de un código lineal sobre GF(2)
#         - capacidad de corrección de errores del código
# Salida: 
#         - tabla de síndromes.
# Esta tabla se proporciona como salida en un diccionario,
# donde las claves (keys) son síndromes y los valores son el error asociado
#
# ... IMPLEMENTAR AQUÍ
def tablaSindromes (M, capacidad): 
    return {}


# Entrada: 
#         - palabra de código de bloque de n bits
#         - matriz de codificación
# Salida: 
#         - array de n bits con el error asociado, de existir, o un array de valores cero
#           de n bits en caso de no haber error.
def calculaError(palabra, M): 
    return palabra



    
# Entrada: 
#         - palabra de un código de bloque de n bits sobre GF(2)
#         - error calculado para dicha palabra con la función anterior
# Salida: 
#         - se calcula la palabra con el error corregido y se devuelve.
def corregir(palabra, error): 
    return palabra

In [19]:
# EJEMPLO 1
# Ejemplos de prueba de envío sin errores

# Generar mensaje a enviar
palabra = GenerarPalabraAleatoria(n)
print("Palabra inicial {}".format(palabra))

# Codificación en código de bloque
M = LeerMatrizCodificacion(FicheroMatrizCodificacion, n, k)
print("Matriz codificación {}".format(M))
palabraCodificada = Codificar(palabra, M)
print("Palabra codificada {}".format(palabraCodificada))

# Cálculo del error y corrección
palabraDecodificada = Decodificar(palabraCodificada, M)
print("Palabra decodificada {}".format(palabraDecodificada))
error = calculaError(palabraDecodificada, M)
print("Error {}".format(error))
corregida = corregir(palabraDecodificada, error)
print("Corregida {}".format(corregida))

# Comprobación con el mensaje del código de bloque enviado por el canal
# Decodificación.
# Comparación con el mensaje del código uniforme generado por la fuente


Palabra inicial [0 1 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 1
 0 1 1 1 1 0 0 0 1 1]
Matriz codificación [[0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 0 0]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 0 0 1]]
Palabra codificada [2 3 2 2 1 2 2 4 3 4 1 3 3 0 4 3 4 1 3 3 1 3 5 3 1 3 1 3 3 3 4 2 3 3 3 3]
Palabra decodificada [3 3 0 4 3 4 1 3 3 1 3 5 3 1 3 1 3 3 3 4 2 3 3 3 3]
Error [3 3 0 4 3 4 1 3 3 1 3 5 3 1 3 1 3 3 3 4 2 3 3 3 3]
Corregida [3 3 0 4 3 4 1 3 3 1 3 5 3 1 3 1 3 3 3 4 2 3 3 3 3]


In [8]:

# EJEMPLO 1

# Ejemplos de prueba de envío sin errores

# Generar mensaje a enviar

# Codificación en código de bloque

# Inserción de un error de 1 bit

# Cálculo del error y corrección


# Comprobación con el mensaje del código de bloque enviado por el canal

# Decodificación.

# Comparación con el mensaje del código uniforme generado por la fuente

In [9]:

# EJEMPLO 1

# Ejemplos de prueba de envío sin errores
dd
# Generar mensaje a enviar

# Codificación en código de bloque

# Inserción de un error de 2 bit

# Cálculo del error y corrección


# Comprobación con el mensaje del código de bloque enviado por el canal

# Decodificación.

# Comparación con el mensaje del código uniforme generado por la fuente

In [10]:

# EJEMPLO 1

# Ejemplos de prueba de envío sin errores

# Generar mensaje a enviar

# Codificación en código de bloque

# Inserción de un error de 3 bit

# Cálculo del error y corrección


# Comprobación con el mensaje del código de bloque enviado por el canal

# Decodificación.

# Comparación con el mensaje del código uniforme generado por la fuente